### ISSUE TITLE
Suggestion: Use GitHub markdown

### ISSUE THREAD

**Issue by semvis123** [einsteinium299/onlineresources#1]
With **GitHub markdown** (`.md`) the files are more easy to read and do not look like plain text anymore.

### Pros: headers
- Easier to read
```py
print('Code blocks, with syntax highlighting')
```
- Lists
- - [x] checkboxes
- [Hyperlinks](https://github.com/einsteinium299/onlineresources/issues/1)
- mentions
- **BOLD text**
- _Italic text_
> "quotes" ~ me 2021

### Cons:
- None?

**Comment by einsteinium299** [comment]
Thanks for the suggestion
